#!/usr/bin/env python3
"""Export land cells from the present-day map's SVG landshape using the standard library.

Sample mainland and island polygons at cell centres; ignore strokes, borders, rivers and lakes.
By default, update the checked-in C++ data. Use --check to detect stale data and --preview
for an SVG overlay of the sampled cells and source coastline.
"""

import argparse
import hashlib
import math
from pathlib import Path
import re
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "docs/map/continent-present.svg"
OUTPUT = ROOT / "src/game/continent-land.generated.hpp"
COLUMNS, ROWS = 384, 256


def read_outline():
    root = ET.parse(SOURCE).getroot()
    extent = tuple(map(float, root.attrib["viewBox"].split()))
    if extent != (0, 0, 2400, 1600):
        raise ValueError("Map coordinates have changed; review the world scale")
    shape = next(e for e in root.iter() if e.get("id") == "landshape")
    # Accept only absolute M/L/Z paths; reject curves and relative coordinates explicitly.
    path = shape.attrib["d"]
    number = r"-?\d+(?:\.\d+)?"
    pair = rf"({number})\s+({number})"
    polygons = []
    for part in path.split("Z")[:-1]:
        if not re.fullmatch(rf"\s*M{pair}(?:\s+L{pair})+\s*", part):
            raise ValueError("landshape must contain closed polygons using absolute M/L/Z commands")
        polygons.append([(float(x), float(y)) for x, y in re.findall(pair, part)])
    if not polygons or path.split("Z")[-1].strip():
        raise ValueError("landshape is empty or contains an unclosed polygon")
    return polygons


def rasterize(polygons):
    grid = [[False] * COLUMNS for _ in range(ROWS)]
    for row in range(ROWS):
        y = (row + 0.5) * 1600 / ROWS
        for polygon in polygons:
            crossings = []
            for a, b in zip(polygon, polygon[1:] + polygon[:1]):
                if (a[1] <= y < b[1]) or (b[1] <= y < a[1]):
                    crossings.append(a[0] + (y - a[1]) * (b[0] - a[0]) / (b[1] - a[1]))
            crossings.sort()
            if len(crossings) % 2:
                raise ValueError("An outline scanline has an odd number of intersections")
            for left, right in zip(crossings[::2], crossings[1::2]):
                start = max(0, math.ceil(left * COLUMNS / 2400 - 0.5))
                end = min(COLUMNS, math.ceil(right * COLUMNS / 2400 - 0.5))
                for column in range(start, end):
                    grid[row][column] = True
    return grid


def land_runs(grid):
    runs = []
    for row, values in enumerate(grid):
        start = None
        for column, land in enumerate(values + [False]):
            if land and start is None:
                start = column
            elif not land and start is not None:
                runs.append((row, start, column))
                start = None
    return runs


def header(runs):
    digest = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    body = "\n".join(f"    {{{row}, {start}, {end}}}," for row, start, end in runs)
    return f"""#pragma once

// Generated by docs/map/export_continent.py; do not edit by hand.
// Source: docs/map/continent-present.svg (landshape, cell-centre sampling).
// SHA256: {digest}
#include <array>
#include <cstddef>
#include <cstdint>

namespace lc1::continent_land {{

inline constexpr std::size_t columns = {COLUMNS};
inline constexpr std::size_t rows = {ROWS};

// Each run is {{row, first column, exclusive end column}}. Unlisted cells are sea.
// clang-format off
inline constexpr std::array<std::array<std::uint16_t, 3>, {len(runs)}> runs{{{{
{body}
}}}};
// clang-format on

}} // namespace lc1::continent_land
"""


def preview(runs, destination):
    root = ET.parse(SOURCE).getroot()
    shape = next(e for e in root.iter() if e.get("id") == "landshape")
    rects = "".join(
        f'<rect x="{start * 6.25}" y="{row * 6.25}" '
        f'width="{(end - start) * 6.25}" height="6.25"/>'
        for row, start, end in runs
    )
    # The world origin is (-3200, -2688); one metre spans 1/2.56 SVG units.
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2400 1600">'
        '<rect width="2400" height="1600" fill="#567e91"/>'
        f'<g fill="#acc17d">{rects}</g>'
        f'<path d="{shape.attrib["d"]}" fill="none" stroke="#fff" stroke-width="1"/>'
        '<g transform="translate(1250 1050) scale(0.390625)">'
        '<rect x="-160" y="-384" width="320" height="384" fill="#a57760"/>'
        '<rect x="-64" y="80" width="128" height="80" fill="#daba7d"/>'
        '<path d="M0 0 V240" stroke="#e6c380" stroke-width="8"/>'
        '<circle cx="0" cy="32" r="12" fill="#ffec59"/></g>'
        '<g fill="white" font-size="26" font-family="sans-serif">'
        '<text x="70" y="70">6144 x 4096 m / 16 m cells</text>'
        '<text x="70" y="110">White: source coastline / Yellow: spawn</text>'
        '</g></svg>\n', encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()
    polygons = read_outline()
    grid = rasterize(polygons)
    runs = land_runs(grid)
    content = header(runs)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("Continent data is stale: run python3 docs/map/export_continent.py")
    else:
        OUTPUT.write_text(content, encoding="utf-8")
    if args.preview:
        preview(runs, args.preview)
    print(f"{len(polygons)} outlines, {sum(map(sum, grid))} land cells, {len(runs)} runs; "
          f"{'data is up to date' if args.check else 'exported'}")


if __name__ == "__main__":
    main()
